version: '3.8'

services:
  # MongoDB Container
  mongodb:
    image: mongo:latest
    container_name: mern-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mern_assessment
    networks:
      - mern-network
    restart: always

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
